### ISSUE TITLE
Feature request: Ability to have role combinations

### ISSUE THREAD

**Issue by AdamJSoftware** [DDtKey/rocket-grants#3]
The ability to have a set of all roles or a one role for a set of roles is great. However, there are certain use cases where having a combination is extremely useful.

For example: [["ROLE_1", "ROLE_2"], ["ROLE_3, "ROLE_4"]]

In this case, a user would have to have (role_1 AND role_2) OR (role_3 AND role_4)

**Comment by DDtKey** [comment]
Thanks for suggestion! 

I'd like to add such feature, but I'd prefer to implement it with more explicit syntax for understanding.

I mean use `AND`/`OR` syntax or probably even better go with classic macro-way: 
`any( all(role_1, role_2), all(role_3, role_4) )`

I think it's just more obvious 🤔

**Comment by AdamJSoftware** [comment]
> Thanks for suggestion!
> 
> I'd like to add such feature, but I'd prefer to implement it with more explicit syntax for understanding.
> 
> I mean use `AND`/`OR` syntax or probably even better go with classic macro-way: `any( all(role_1, role_2), all(role_3, role_4) )`
> 
> I think it's just more obvious 🤔

Absolutely, pretty new to rust so I'm not too familiar with all of the syntax and conventions. But that does seem more obvious. You have my vote

**Comment by DDtKey** [comment]
It took a year and finally the feature is almost ready to use, I was able to spend some time improving the `*-grants` ecosystem.
So it will be available soon on `crates.io`

Unfortunately, some breaking changes are expected because of multiple reasons. I wanted to cleanup and align crates
